# Generated by Django 3.2 on 2022-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_play_music', models.CharField(default='0', max_length=150, verbose_name='تعداد موزیک های پخش شده')),
            ],
        ),
    ]
